[package]
name = "balls"
version = "3.0.0"
edition = "2021"

[dependencies]
bitflags = { version = "2.6.0", features = ["std"] }
compio = { version = "0.12.0", features = ["macros", "nightly"] }
euclid = "0.22.11"
futures-util = "0.3.30"
rand = { version = "0.8.5", features = ["nightly"] }
rand_distr = "0.4.3"
winio = { version = "0.1.0", features = ["nightly"] }
